version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
      eslint:
        patterns:
          - "eslint*"
      vite:
        patterns:
          - "vite*"
      vitest:
        patterns:
          - "vitest*"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "ci"
