blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/DavidAmunga/kenya-locations/discussions
    about: Ask questions, share ideas, and discuss with the community
  - name: Documentation
    url: https://kenya-locations.web.app
    about: Read the full documentation
